# -*- coding: utf-8 -*-
"""d3 - eda

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11L8YN6cQ0gfeiyWKsz5IDLHYLoUyFeTq
"""

from google.colab import drive
drive.mount('/content/drive')

import os

folder_path = '/content/drive/MyDrive/Patient Safety Data - Muckrock/data/Device_data'

# Check if the folder exists
if os.path.exists(folder_path):
    print(f"Listing contents of '{folder_path}':")
    for item in os.listdir(folder_path):
        print(item)
else:
    print(f"Folder not found at '{folder_path}'. Please check the path and ensure Google Drive is mounted correctly. If this is a 'Shared with me' folder, ensure you have created a shortcut to it in your 'My Drive'.")

file_path = "Device_data/DEVICE2024.txt"

combined_content = []

if os.path.exists(folder_path):
    for filename in os.listdir(folder_path):
        if filename.endswith('.txt'):
            file_path = os.path.join(folder_path, filename)
            try:
                with open(file_path, 'r', encoding='latin-1') as f: # Changed encoding to 'latin-1'
                    combined_content.append(f.read())
                print(f"Successfully read: {filename}")
            except Exception as e:
                print(f"Error reading {filename}: {e}")

    all_text = "\n".join(combined_content)
    print(f"\nCombined content (first 500 characters):\n{all_text[:500]}...")
    print(f"\nTotal combined content length: {len(all_text)} characters")
else:
    print(f"Folder not found at '{folder_path}'. Please check the path.")

output_file_path = os.path.join('/content/drive/MyDrive/', 'combined_device_data.txt')

if 'all_text' in locals() and all_text:
    with open(output_file_path, 'w', encoding='utf-8') as f:
        f.write(all_text)
    print(f"Combined content saved to: {output_file_path}")
else:
    print("No combined content to save. Please ensure the previous cell executed successfully.")

file_path = '/content/drive/MyDrive/Patient Safety Data - Muckrock/data/Device_data/combined_device_data.txt'

with open(file_path, 'r', encoding='utf-8') as f:
    print(f"First 5 lines of '{file_path}':")
    for i, line in enumerate(f):
        if i >= 5:
            break
        print(line.strip())

import pandas as pd

data = pd.read_csv(file_path, sep='|', low_memory=False, on_bad_lines='skip')
print("DataFrame loaded successfully. Displaying the first 5 rows:")
print(data.head())

data.describe()

years = data['DATE_REMOVED_YEAR'].unique()
years

#2015 onwards
#discrepancy between date removed years